models/ShortLink.php
<?php

namespace app\models;

use yii\db\ActiveRecord;
use yii\base\NotSupportedException;

/**
 * Class ShortLink
 * @package app\models
 * @property integer $id
 * @property string $code
 * @property string $redirect_url
 * @property string $expired_at
 */
class ShortLink extends ActiveRecord
{
    /**
     * @param int $length
     * @return bool|string
     */
    public static function generateCode($length = 5)
    {
        return substr(str_shuffle("0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"), 0, $length);
    }

    /**
     * @inheritdoc
     */
    public function save($runValidation = true, $attributeNames = null)
    {
        $isRetrySave = empty($this->code);
        try{
            if(empty($this->code)){
                $this->code = static::generateCode();
            }
            $result = parent::save($runValidation, $attributeNames);
        } catch (\Exception $e){
            /** Try to remove the collision */
            if($e->getCode() === static::getDuplicateCodeError()){
                if($isRetrySave){
                    $this->code = static::generateCode();
                    return parent::save($runValidation, $attributeNames);
                } else {
                    $this->addError('code', 'Duplicate code key');
                    return false;
                }
            }

            throw $e;
        }

        return $result;
    }

    /**
     * @return int
     * @throws NotSupportedException
     */
    public static function getDuplicateCodeError()
    {
        $schema = static::getDb()->getSchema();
        if($schema instanceof \yii\db\sqlite\Schema){
            return 23000;
        }
        if($schema instanceof \yii\db\mysql\Schema){
            return 1062;
        }

        throw new NotSupportedException('Undefined error code for ' . $schema::className());
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\forms\ShortLinkForm;
use app\models\ShortLink;
use Yii;
use yii\db\QueryBuilder;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * Class SiteController
 * @package app\controllers
 */
class SiteController extends Controller
{
    /**
     * @return string
     * @throws \Exception
     */
    public function actionIndex()
    {
        $form = new ShortLinkForm();

        if($form->load(Yii::$app->request->post()) && $form->validate()){
            $model = new ShortLink();
            $model->code = $form->code;
            $model->redirect_url = $form->redirectUrl;
            $model->expired_at = $form->expiredAt;

            if($model->save()){
                return $this->render('index', ['form' => $form, 'model' => $model]);
            } elseif($model->hasErrors()){
                $form->addError('code', 'Короткая ссылка уже существует');
            } else {
                Yii::error('Ошибка добавления ссылки: ' . VarDumper::dumpAsString($form->attributes));
                $form->addError('code', 'Произошла неизвестная ошибка, попробуйте еще раз');
            }
        }

        return $this->render('index', ['form' => $form]);
    }

    /**
     * @param $code
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionLink($code)
    {
        /** @var ShortLink|null $shortLink */
        $shortLink = ShortLink::find()
            ->where(['code' => $code])
            ->andWhere(['or', ['>=', 'expired_at', date('Y-m-d H:i')], ['is', 'expired_at', null]])
            ->one();

        if($shortLink){
            return $this->redirect($shortLink->redirect_url);
        }

        throw new NotFoundHttpException('Short link does not exist');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="container">
    <?= $content ?>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/index.php
<?php
/**
 * @var \app\forms\ShortLinkForm $form
 * @var \app\models\ShortLink|null $model
 */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

$activeForm = ActiveForm::begin() ?>

<div class="row">
    <div class="col-lg-4">

        <?= $activeForm->field($form, 'code') ?>
        <?= $activeForm->field($form, 'redirectUrl') ?>
        <?= $activeForm->field($form, 'expiredAt') ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Уменьшить') ?>
            </div>
        </div>

        <? if($model):?>
            Ссылка:
            <a href="<?= Url::toRoute(['site/link', 'code' => $model->code])?>">
                <?= Url::toRoute(['site/link', 'code' => $model->code])?>
            </a>
        <? endif?>

    </div>
</div>

<?php ActiveForm::end() ?>